import test from 'node:test';
import assert from 'node:assert/strict';
import {loadScenarios} from '../scripts/scenarios.mjs';
import {createEngine} from '../src/engine.js';
import {validateScenario} from '../src/schema.js';
const configs=(await loadScenarios()).filter(c=>c.design);
const setup=id=>{const c=configs.find(c=>c.id===id);return {c,e:createEngine(c)};};
function plan(c,s,id){
 const a=c.actions.find(a=>a.id===id),r=a.judgment?.[0];
 return r?{hypothesis:r.hypotheses[0],purpose:r.purposes[0],evidenceIds:s.evidence.filter(e=>r.evidence.includes(e.kind)).map(e=>e.id),prediction:'down',guard:'3分後に遅延と失敗率を確認し、悪化なら方針を変更する。'}:{};
}
function run(c,ids,reasoned=true){const e=createEngine(c);let s=e.initialState();for(const id of ids)s=e.step(s,id,reasoned?plan(c,s,id):{});return {e,s};}
for(const c of configs){
 for(const name of ['expert','alternative','accidental'])test(`${c.id} ${name} path reaches sustained recovery`,()=>{const {e,s}=run(c,c.design.paths[name].actions,name!=='accidental');assert.equal(e.isStable(s),true);assert.equal(e.finish(s).endReason,'recovered');assert.ok(s.failures>0);const out=JSON.parse(e.exportRun(e.finish(s)));assert.equal(out.definition.design.paths[name].note,c.design.paths[name].note);assert.ok(out.review.outcome);});
 test(`${c.id} investigation without intervention times out with impact`,()=>{const {e,s}=run(c,c.design.paths.overInvestigation.actions);assert.equal(s.endReason,'timeout');assert.equal(e.isStable(s),false);assert.ok(s.failures>100);assert.equal(s.decisions.at(-1).completed,false);});
 test(`${c.id} dangerous path improves immediately and then deteriorates`,()=>{const {e,s}=run(c,c.design.paths.dangerous.actions);const d=s.decisions.find(d=>d.group==='act');assert.ok(d.after.p99<d.before.p99);assert.ok(e.metrics(s).p99>d.after.p99);assert.equal(e.isStable(s),false);assert.match(e.review(s).details[0].comments.join('\n'),/完了時.*再観測/);});
 test(`${c.id} supported decisions score above accidental recovery`,()=>{const good=run(c,c.design.paths.expert.actions),lucky=run(c,c.design.paths.accidental.actions,false);assert.ok(good.e.review(good.s).scores[0].value>lucky.e.review(lucky.s).scores[0].value);});
}
test('schema-aware rollback without compatibility expands errors to every request',()=>{const {e,c}=setup('004');let s=e.step(e.initialState(),'schema');s=e.step(s,'rollback',plan(c,s,'rollback'));assert.equal(e.metrics(s).error,100);const detail=e.review(s).details[0];assert.equal(detail.safety,0);assert.ok(detail.diagnostic<=4);assert.match(detail.comments.join('\n'),/旧列名/);});
test('compatible rollback is a valid different decision at the same action',()=>{const {e,c}=setup('004');let s=e.step(e.initialState(),'schema');s=e.step(s,'compat');s=e.step(s,'rollback',plan(c,s,'rollback'));assert.equal(e.metrics(s).error,.2);assert.equal(e.review(s).details[1].diagnostic,10);assert.ok(e.review(s).details[1].safety>0);});
test('compatibility fix after draining restores routing capacity and accounts for cutover',()=>{const {e}=setup('004');let s=e.step(e.initialState(),'drain');s=e.step(s,'wait');s=e.step(s,'compat');assert.equal(s.oldPercent,20);assert.equal(s.drained,false);assert.equal(e.metrics(s).error,.2);assert.equal(s.extraCost,4);assert.ok(s.events.some(x=>x.text.includes('4%以上')));s=e.step(e.step(s,'wait'),'wait');assert.equal(e.isStable(s),true);});
test('circuit produces fast errors, never recovery, and needs controlled reopening',()=>{const {e,c}=setup('005');let s=e.step(e.initialState(),'config');s=e.step(s,'circuit');s=e.step(e.step(s,'wait'),'wait');assert.equal(e.metrics(s).p99,.05);assert.equal(e.metrics(s).error,100);assert.equal(s.featureMinutes,4);assert.equal(e.isStable(s),false);assert.match(e.review(s).outcome,/100%失敗/);s=e.step(s,'close',plan(c,s,'close'));assert.equal(e.metrics(s).error,25);assert.equal(e.review(s).details.at(-1).safety,2);});
test('dependency recovery does not cure retry amplification; budget drains over time',()=>{const {e}=setup('005');let s=e.step(e.initialState(),'wait');s=e.step(s,'dependency');assert.equal(e.metrics(s).providerProbeError,.2);assert.equal(e.metrics(s).error,25);s=e.step(s,'budget');assert.equal(e.metrics(s).error,8);s=e.step(s,'wait');assert.equal(e.metrics(s).error,8);s=e.step(s,'wait');assert.equal(e.metrics(s).error,.3);assert.equal(e.isStable(s),false);s=e.step(s,'wait');assert.equal(e.isStable(s),true);});
test('deadlock concurrency mitigation preserves service but records unresolved cause',()=>{const {e}=setup('003');let s=e.step(e.initialState(),'serialize');s=e.step(e.step(s,'wait'),'wait');assert.equal(e.isStable(s),true);assert.equal(s.fixed,false);assert.equal(e.metrics(s).deadlocks,1);assert.match(e.review(s).outcome,/待ち時間/);});
test('filling every field with an unsupported hypothesis cannot get high reasoning marks',()=>{const {e}=setup('005');let s=e.step(e.step(e.initialState(),'attempts'),'config');s=e.step(s,'budget',{hypothesis:'capacity',purpose:'cause',prediction:'down',guard:'再確認',evidenceIds:s.evidence.map(e=>e.id)});assert.equal(e.review(s).details[0].diagnostic,4);});
test('later evidence cannot retroactively justify a decision or create a known hazard',()=>{const {e}=setup('004');let s=e.step(e.initialState(),'rollback',{hypothesis:'schema',purpose:'cause',prediction:'down',guard:'再確認',evidenceIds:['e1']});const before=e.review(s).details[0];s=e.step(s,'schema');const after=e.review(s).details[0];assert.equal(after.diagnostic,before.diagnostic);assert.equal(after.evidence,false);assert.ok(after.safety>0);assert.equal(s.decisions[0].knownEvidence.length,1);assert.equal(s.decisions[0].beforeState.compatible,false);});
test('execution costs are charged even when a long action is interrupted',()=>{const {c}=setup('004');const e=createEngine(c);let s=e.initialState();for(let i=0;i<14;i++)s=e.step(s,'wait');s=e.step(s,'compat');assert.equal(s.extraCost,4);assert.equal(s.compatible,false);assert.equal(s.decisions.at(-1).completed,false);});
test('schema validates rule evidence, hypothesis, caps, cost and documented paths',()=>{const {c}=setup('004');for(const change of [x=>x.actions.find(a=>a.id==='rollback').judgment[0].evidence=['missing'],x=>x.actions.find(a=>a.id==='rollback').judgment[0].hypotheses=['missing'],x=>x.actions.find(a=>a.id==='rollback').hazards[0].safetyCap=11,x=>x.actions[0].cost=-1,x=>x.design.paths.expert.actions=['missing']]){const bad=structuredClone(c);change(bad);assert.throws(()=>validateScenario(bad));}});
for(const [id,repair] of [['003',['locks','changes','fix','wait','wait']],['004',['schema','compat','wait','wait']],['005',['attempts','config','budget','wait','wait','wait']]])test(`${id} player can revise after the tempting intervention fails`,()=>{const {c}=setup(id);const {e,s}=run(c,[...c.design.paths.dangerous.actions,...repair]);assert.equal(e.isStable(s),true);assert.equal(e.finish(s).endReason,'recovered');assert.equal(e.review(s).details.length,2);assert.ok(s.time<c.limits.minutes);});
test('version observations reflect later overload even after schema compatibility was restored',()=>{const {e}=setup('004');let s=e.step(e.initialState(),'compat');s=e.step(s,'drain');s=e.step(s,'wait');s=e.step(s,'versions');assert.equal(e.metrics(s).error,12);assert.match(s.evidence.at(-1).text,/12%/);assert.doesNotMatch(s.evidence.at(-1).text,/とも500は収束/);});
