import {createEngine} from './engine.js';
let scenario, catalogue=[], actions=[], hypotheses={}, state, initialState, metrics, available, step, finish, review, exportRun, describe, isStable;
let started=false,selected='',filter='observe',tab='evidence',message='',draft={},showExport=false,loading=true,loadError='';
const el=document.querySelector('#app');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const time=n=>`${String(Math.floor(n)).padStart(2,'0')}:${String(Math.round((n%1)*60)).padStart(2,'0')}`;
const selectedOpt=(a,b)=>a===b?' selected':'';
function chart(){
 const c=scenario.display.chart,limit=scenario.limits.minutes;
 const samples=state.history.filter((p,i,arr)=>i===arr.length-1||arr[i+1].time!==p.time);
 const y=value=>125-Math.min(c.max,value)/c.max*105;
 const pts=samples.map(p=>`${40+p.time/limit*680},${y(p[c.metric])}`).join(' ');
 return `<svg viewBox="0 0 750 155" role="img" aria-label="${esc(c.label)}の推移。横軸0から${limit}分、縦軸0から${c.max}${esc(c.unit)}。"><text x="0" y="24">${c.max}${esc(c.unit)}</text><text x="0" y="77">${c.max/2}${esc(c.unit)}</text><text x="0" y="128">0</text><path d="M40 20H720 M40 72H720 M40 125H720" class="gridline"/><path d="M40 ${y(c.threshold)}H720" class="targetline"/><polyline points="${pts}" class="trend"/>${samples.map(p=>`<circle cx="${40+p.time/limit*680}" cy="${y(p[c.metric])}" r="3" class="point"><title>${time(p.time)} ${esc(c.label)} ${p[c.metric]}${esc(c.unit)}</title></circle>`).join('')}<text x="40" y="150">00:00</text><text x="365" y="150">${time(limit/2)}</text><text x="681" y="150">${time(limit)}</text></svg>`;
}
function scenarioPicker(){return `<div class="scenario-picker"><label for="scenario-select">シナリオを選ぶ</label><select id="scenario-select">${catalogue.map(c=>`<option value="${esc(c.id)}"${selectedOpt(c.id,scenario.id)}>#${esc(c.id)} · ${esc(c.title)} — ${esc(c.durationLabel)}</option>`).join('')}</select><p>シナリオを選び、観測から対応を始めてください。</p></div>`;}
function header(){return `<header><a class="brand" href="/" aria-label="Engineering Judgment ホーム"><span class="mark">ej<span>↗</span></span> ENGINEERING JUDGMENT</a><span class="header-note">FLIGHT SIMULATOR <span class="pill">PROTOTYPE 0.1</span></span></header>`;}
function intro(){return `${header()}<main class="intro"><div class="eyebrow">SCENARIO ${esc(scenario.id)} / ${esc(scenario.audience)}</div>${scenarioPicker()}<h1>その判断の、<br><span>次に起きること。</span></h1><p class="lead">${esc(scenario.lead).replaceAll('\n','<br>')}</p><div class="intro-layout"><section class="brief"><div class="eyebrow">INCOMING INCIDENT</div><h2>${esc(scenario.title)}</h2><p>${esc(scenario.description)}</p><div class="intro-metrics">${scenario.display.cards.slice(0,3).map(c=>`<div><small>${esc(c.label)}</small><strong>${metrics(state)[c.metric]}<span>${esc(c.unit)}</span></strong></div>`).join('')}</div><button class="primary" id="start">インシデントに入る <span>↗</span></button><p class="muted small">${esc(scenario.durationLabel)} / アカウント不要 / この端末内で実行</p></section><aside class="intro-guide"><h3>答えより、判断の過程を。</h3><ol><li><b>観測する</b><span>限られた情報から仮説を立てる。</span></li><li><b>調べ、介入する</b><span>行動には時間と副作用がある。</span></li><li><b>結果から考え直す</b><span>一時改善が復旧とは限らない。</span></li><li><b>判断を振り返る</b><span>当時の証拠と結果を照らし合わせる。</span></li></ol></aside></div><p class="intro-footer">時間は行動で進みます。考えている間は進みません。<br>自動評価は記録の代理指標です。実務能力や採用適性の判定には使いません。再読み込みで記録は消えるため、終了時に保存してください。</p></main>`;}
function metricCards(){const m=metrics(state);return `<div class="metrics">${scenario.display.cards.map(c=>`<div class="metric"><small>${esc(c.label)}</small><strong>${m[c.metric]}<span>${esc(c.unit)}</span></strong><span class="metric-note">${esc(describe(c.note,state))}</span></div>`).join('')}</div>`;}
function decisionForm(){
 const a=actions.find(x=>x.id===selected);
 return `<section class="decision"><div class="section-title"><h3>判断を記録</h3><span class="muted small">任意・実行前に保存</span></div><form id="decision-form"><label>現在の仮説<select name="hypothesis">${Object.entries(hypotheses).map(([id,label])=>`<option value="${id}"${selectedOpt(draft.hypothesis||'unknown',id)}>${label}</option>`).join('')}</select></label><div class="form-row"><label>今回の目的<select name="purpose">${[['investigate','情報を集める'],['mitigate','顧客影響を軽減'],['cause','原因に対応']].map(([v,l])=>`<option value="${v}"${selectedOpt(draft.purpose||'investigate',v)}>${l}</option>`).join('')}</select></label><label>完了直後の${esc(scenario.scoring.predictionMetric)}予測<select name="prediction"><option value="">未記録</option>${[['down','下がる'],['same','ほぼ変わらない'],['up','上がる']].map(([v,l])=>`<option value="${v}"${selectedOpt(draft.prediction,v)}>${l}</option>`).join('')}</select></label></div><fieldset><legend>この判断で使う証拠</legend><div class="evidence-choices">${state.evidence.map(e=>`<label class="check"><input type="checkbox" name="evidenceIds" value="${e.id}"${draft.evidenceIds?.includes(e.id)?' checked':''}> <span>${time(e.time)} ${esc(e.title)}</span></label>`).join('')}</div></fieldset><label>理由・比較した別の仮説<textarea name="note" rows="2" placeholder="何を確かめるために、この行動を選ぶか">${esc(draft.note)}</textarea></label><label>結果の確認・中止条件<input name="guard" value="${esc(draft.guard)}" placeholder="どの指標を、いつ確認して方針を変えるか"></label><div class="execute"><span><b>${esc(a.label)}</b><small>時間 +${a.duration}分</small></span><button class="primary" type="submit"${!available(state,a.id)?' disabled':''}>実行 →</button></div></form></section>`;
}
function evidencePanel(){return `<div class="evidence-list">${[...state.evidence].reverse().map(e=>`<article class="evidence-card"><div><span class="evidence-time">${time(e.time)}</span><b>${esc(e.title)}</b></div><p>${esc(e.text)}</p></article>`).join('')}</div>`;}
function timeline(aar=false){const r=aar?review(state):null;return `<div class="timeline"><article><time>00:00</time><div><b>インシデント開始</b><p>${esc(state.evidence[0].text)}</p></div></article>${[...state.decisions.map(d=>({...d,sortTime:d.start})),...state.events.map(e=>({...e,sortTime:e.time,isEvent:true}))].sort((a,b)=>a.sortTime-b.sortTime).map(d=>{
 if(d.isEvent)return `<article class="event"><time>${time(d.time)}</time><div>${esc(d.text)}</div></article>`;
 const detail=r?.details.find(x=>x.decisionId===d.id);
 return `<article><time>${time(d.start)}<span>↓ ${time(d.end)}</span></time><div><b>${esc(d.label)}${d.completed?'':'（未完了）'}</b><p>${esc(hypotheses[d.plan.hypothesis])} · ${esc(scenario.display.chart.label)} ${d.before[scenario.display.chart.metric]}${esc(scenario.display.chart.unit)} → ${d.after[scenario.display.chart.metric]}${esc(scenario.display.chart.unit)}</p>${d.plan.note?`<blockquote>${esc(d.plan.note)}</blockquote>`:''}<details><summary>当時の判断と証拠</summary><p>目的：${esc({investigate:'情報収集',mitigate:'顧客影響の軽減',cause:'原因対応'}[d.plan.purpose])} / 予測：${esc({down:'低下',same:'変化なし',up:'上昇'}[d.plan.prediction]||'未記録')}</p><p>確認条件：${esc(d.plan.guard||'未記録')}</p>${d.knownEvidence.filter(e=>d.plan.evidenceIds.includes(e.id)).map(e=>`<p class="small">[${time(e.time)} ${esc(e.title)}] ${esc(e.text)}</p>`).join('')||'<p class="small">引用なし</p>'}</details>${detail?`<div class="feedback">${detail.matched!==null?`<p>直後の予測：${detail.matched?'結果と一致':'結果と不一致'}。遅延して現れる影響は下の推移も参照。</p>`:''}${detail.comments.map(c=>`<p>${esc(c)}</p>`).join('')}</div>`:''}</div></article>`;
 }).join('')}</div>`;}
function workspace(){return `${header()}<main class="workspace"><div class="scene-heading"><div><div class="eyebrow">SCENARIO ${esc(scenario.id)} <span class="live-dot"></span> INCIDENT ROOM</div><h1>${esc(scenario.title)}</h1></div><div class="clock"><small>SIMULATION TIME</small><strong>${time(state.time)} <span>/ ${time(scenario.limits.minutes)}</span></strong></div></div><div class="statusbar"><span><i class="${isStable(state)?'good':'warn'}"></i>${isStable(state)?`健全状態が${scenario.limits.stableMinutes}分以上継続`:state.stableMinutes?`健全状態を確認中 · ${state.stableMinutes}/${scenario.limits.stableMinutes}分`:'インシデント対応中'}</span><span>${esc(describe(scenario.display.status,state))}</span><span>追加費用 ${state.extraCost}単位</span><span>失敗試行 ≈${Math.round(state.failures)}件</span></div>${metricCards()}<div class="main-grid"><div class="left-column"><section class="panel trend-panel"><div class="section-title"><h2>結果を観測する</h2><span class="legend">● ${esc(scenario.display.chart.label)} <span>─ 健全閾値 ${scenario.display.chart.threshold}${esc(scenario.display.chart.unit)}</span></span></div>${chart()}<p class="small muted">行動の完了時点で更新。失敗試行はerror率からの概算で、売上損失ではありません。</p></section><section class="panel findings"><div class="tabs"><button data-tab="evidence" class="${tab==='evidence'?'active':''}">証拠ノート <span>${state.evidence.length}</span></button><button data-tab="timeline" class="${tab==='timeline'?'active':''}">判断の履歴 <span>${state.decisions.length}</span></button></div>${tab==='evidence'?evidencePanel():timeline()}</section></div><aside class="panel actions-panel"><div class="section-title"><h2>次の一手を選ぶ</h2><span class="small muted">行動ごとに時間が進む</span></div><div class="filters">${[['observe','観測'],['talk','相談'],['act','介入']].filter(([id])=>actions.some(a=>a.group===id)).map(([id,label])=>`<button data-filter="${id}" class="${filter===id?'active':''}">${label}</button>`).join('')}</div><div class="action-list">${actions.filter(a=>a.group===filter).map(a=>`<button class="action ${selected===a.id?'selected':''}" data-action="${a.id}"${!available(state,a.id)?' disabled':''}><span><b>${esc(a.label)}</b><small>${esc(a.description)}</small></span><span class="duration">${a.duration}分</span></button>`).join('')}</div>${decisionForm()}</aside></div><footer class="run-footer"><span class="small muted">考えている間は時間が進みません。記録はこのページ内に保持されます。</span><div><button class="subtle" id="export">記録を保存</button><button class="subtle" id="show-export">JSONを表示</button><button class="secondary" id="finish">${isStable(state)?'復旧を宣言して振り返る':'対応を終了して振り返る'}</button></div></footer></main>`;}
function aar(){const r=review(state);return `${header()}<main class="review"><div class="eyebrow">AFTER ACTION REVIEW / SCENARIO ${esc(scenario.id)}</div><div class="scene-heading"><div><h1>結果から、判断を振り返る。</h1><p class="lead">${state.endReason==='recovered'?'復旧を確認しました。':state.endReason==='timeout'?`${scenario.limits.minutes}分の対応時間が終了しました。`:'対応を途中で終了しました。'} 当時見えていた証拠に立ち戻ります。</p></div><div class="export-buttons"><button class="primary" id="export">記録を保存 ↓</button><button class="subtle" id="show-export">JSONを表示</button></div></div><div class="statusbar"><span>${r.stable?`健全状態が${scenario.limits.stableMinutes}分以上継続`:'安定復旧は未確認'}</span><span>経過 ${time(state.time)}</span><span>失敗試行 ≈${Math.round(state.failures)}件</span><span>追加費用 ${state.extraCost}単位</span><span>機能停止 ${state.featureMinutes}分</span></div><p class="muted small">以下は暫定ルールによる記録の代理評価です。実務能力の測定値ではありません。未記録は「考えていなかった」ことを意味しません。</p><div class="score-grid">${r.scores.map(s=>`<article class="panel score"><h3>${s.name}</h3><strong>${s.value??'—'}<span>${s.value===null?'未評価':'/ 10'}</span></strong><div class="score-track"><i style="width:${(s.value||0)*10}%"></i></div><p>${esc(s.why)}</p></article>`).join('')}</div><section class="panel reveal"><div class="eyebrow">WHAT HAPPENED</div><h2>${esc(scenario.review.title)}</h2><p>${esc(r.rootCause)}</p><p class="muted small">これは条件を固定した教育用モデルです。実環境で同じ数値・経過になるとは限りません。</p></section><div class="review-grid"><section class="panel"><h2>意思決定のタイムライン</h2>${timeline(true)}</section><div><section class="panel"><h2>${esc(scenario.display.chart.label)}の推移</h2>${chart()}<details><summary>各分のメトリクスを確認</summary><div class="table-scroll"><table><thead><tr><th>時刻</th><th>${esc(scenario.display.chart.label)}</th><th>出来事</th></tr></thead><tbody>${state.history.map(p=>`<tr><td>${time(p.time)}</td><td>${p[scenario.display.chart.metric]}${esc(scenario.display.chart.unit)}</td><td>${esc(p.event||'—')}</td></tr>`).join('')}</tbody></table></div></details></section><section class="panel reflection"><h2>次の障害へ持ち帰る</h2><label for="reflection">${esc(scenario.review.reflectionPrompt).replaceAll('\n','<br>')}</label><textarea id="reflection" rows="7" placeholder="結果と予測が違った場面から考えてみる">${esc(state.reflection)}</textarea><p class="muted small">自動採点せず、保存する記録に含めます。${esc(scenario.review.followUp)}</p></section></div></div><footer class="run-footer"><p class="small muted">再プレイは同じ条件です。未知の障害への転移は、この1本では検証できません。</p><div><button class="subtle" id="choose-scenario">シナリオを選び直す</button><button class="secondary" id="restart">同じ条件でもう一度</button></div></footer></main>`;}
function getDraft(){const form=document.querySelector('#decision-form');if(!form)return;const f=new FormData(form);draft={...Object.fromEntries(f),evidenceIds:f.getAll('evidenceIds')};}
function render(){
 if(loading||loadError){el.innerHTML=`${header()}<main><h1>${loadError?'シナリオを読み込めません':'シナリオを読み込み中…'}</h1>${loadError?`<pre class="load-error">${esc(loadError)}</pre><a href="/">一覧を読み直す</a>`:''}</main>`;return;}

 el.innerHTML=(!started?intro():state.ended?aar():workspace())+(showExport?`<section class="panel export-panel"><h2>記録のJSON</h2><p>ダウンロードできない場合は、以下をコピーして .json ファイルに保存できます。</p><textarea aria-label="保存用JSON" rows="10" readonly>${esc(exportRun(state))}</textarea><button class="subtle" id="hide-export">閉じる</button></section>`:'')+`<div class="toast" role="status" aria-live="polite">${esc(message)}</div>`;
 document.querySelector('#scenario-select')?.addEventListener('change',e=>loadScenario(e.target.value));
 document.querySelector('#choose-scenario')?.addEventListener('click',()=>{if(!window.confirm('別のシナリオへ移ります。必要な記録は先に保存してください。'))return;started=false;state=initialState();showExport=false;draft={};message='';render();window.scrollTo(0,0);});
 document.querySelector('#start')?.addEventListener('click',()=>{started=true;render();});
 document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{getDraft();filter=b.dataset.filter;selected=actions.find(a=>a.group===filter&&available(state,a.id))?.id||actions.find(a=>a.group===filter).id;render();});
 document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>{getDraft();selected=b.dataset.action;render();});
 document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{getDraft();tab=b.dataset.tab;render();});
 document.querySelector('#decision-form')?.addEventListener('submit',e=>{e.preventDefault();getDraft();const a=actions.find(a=>a.id===selected);try{state=step(state,selected,draft);}catch(error){message=`行動を実行できません: ${error.message}`;render();return;}draft={hypothesis:draft.hypothesis};message=`${a.label}を${state.decisions.at(-1).completed?'完了':'時間切れで中断'}。時刻 ${time(state.time)}。`;if(!available(state,selected)){selectDefault();}render();});
 document.querySelector('#finish')?.addEventListener('click',()=>{if(!isStable(state)&&!window.confirm('安定復旧は未確認です。対応を終了して振り返りますか？'))return;state=finish(state);message='';render();window.scrollTo(0,0);});
 document.querySelector('#reflection')?.addEventListener('input',e=>{state.reflection=e.target.value;});
 document.querySelector('#export')?.addEventListener('click',()=>{const url=URL.createObjectURL(new Blob([exportRun(state)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`engineering-judgment-${scenario.id}-${state.time}min.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);message='保存を開始しました。ダウンロードできない場合は「JSONを表示」を使ってください。';getDraft();render();});
 document.querySelector('#show-export')?.addEventListener('click',()=>{getDraft();showExport=true;render();document.querySelector('.export-panel').scrollIntoView({block:'center'});});
 document.querySelector('#hide-export')?.addEventListener('click',()=>{getDraft();showExport=false;render();});
 document.querySelector('#restart')?.addEventListener('click',()=>{if(!window.confirm('現在の記録をリセットします。必要な記録は先に保存してください。'))return;state=initialState();draft={};showExport=false;selectDefault();tab='evidence';message='';render();window.scrollTo(0,0);});
}
window.addEventListener('beforeunload',e=>{if(started&&state.decisions.length){e.preventDefault();e.returnValue='';}});
function selectDefault(){const a=actions.find(a=>a.group==='observe'&&available(state,a.id))||actions.find(a=>available(state,a.id))||actions[0];selected=a.id;filter=a.group;}
async function getJSON(url){const response=await fetch(url,{cache:'no-store'});const result=await response.json();if(!response.ok)throw new Error(result.error||'読み込みに失敗しました');return result;}
async function loadScenario(id){
 loading=true;loadError='';render();
 try{
  const definition=await getJSON(`/api/scenarios/${encodeURIComponent(id)}`);
  const engine=createEngine(definition);
  scenario=definition;document.title=`Engineering Judgment — Scenario ${scenario.id}`;actions=scenario.actions;hypotheses=scenario.hypotheses;
  ({initialState,metrics,available,step,finish,review,exportRun,describe,isStable}=engine);
  state=initialState();started=false;draft={};showExport=false;message='';tab='evidence';selectDefault();
  history.replaceState(null,'',`?scenario=${encodeURIComponent(scenario.id)}`);
 }catch(error){loadError=error.message;}
 loading=false;render();
}
async function startApp(){
 render();
 try{catalogue=await getJSON('/api/scenarios');await loadScenario(new URLSearchParams(location.search).get('scenario')||catalogue[0].id);}
 catch(error){loading=false;loadError=error.message;render();}
}
startApp();
